# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI / CD DEVOPS Development

on:
  push:
    branches: [ feature/* ]
jobs:
  SEGURIDAD:
    name: Seguridad
    runs-on: ubuntu-latest
    steps:
    - name: clone repo
      uses: actions/checkout@v2
    - name: tfsec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        soft_fail: true
  COSTOS:
    name: Costo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Infracost-setup
      uses: infracost/actions/setup@v2
      with:
        api-key: ${{ secrets.INFRACOST_API_KEY }}
    - name: generate infracost estimate
      uses: infracost breakdown --path=.
  TERRFORM_PLAN:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
