name: CI DEVOPS Development

on:
  push:
    branches: [ feature/* ]
jobs:
  SEGURIDAD:
    name: Seguridad
    runs-on: ubuntu-latest
    steps:
    - name: clone repo
      uses: actions/checkout@v3
    - name: tfsec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        soft_fail: true
  COSTOS:
    name: Costo
    needs: SEGURIDAD
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Infracost-setup
      uses: infracost/actions/setup@v2
      with:
        api-key: ${{ secrets.INFRACOST_API_KEY }}
    - name: generate infracost estimate
      run: infracost breakdown --path=.
  TEST:
    name: Terraform Test
    needs: [SEGURIDAD, COSTOS]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: 1.21
    - uses: actions/checkout@v3
    - name: Instalar terraform
      uses: hashicorp/setup-terraform@v2
    - name: Download Go Modules
      working-directory: tfmtest/test
      run: go mod download
    - name: Run Go Tests
      working-directory: tfmtest/test
      run: go test -v -tags=unit
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

  TERRFORM_VALIDATE_PLAN:
    name: Terraform validacion y terrform plan
    needs: [SEGURIDAD, COSTOS]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Instalar terraform
      uses: hashicorp/setup-terraform@v2
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: terraform init
      run: terraform init
    - name: terraform validate
      run: terraform validate
    - name: terraform plan
      run: terraform plan

    
        

